# Generated by Django 6.0 on 2026-01-12 03:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_governingbody_photo_alter_staff_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='teachers'),
        ),
    ]
