# Generated by Django 6.0 on 2026-01-12 04:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governingbody',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='governing_body'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='staff'),
        ),
    ]
