# Generated by Django 6.0 on 2025-12-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('routine', models.FileField(upload_to='class_routine/')),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
