# Generated by Django 6.0 on 2026-01-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_class_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/homepage/')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/library/')),
            ],
        ),
        migrations.CreateModel(
            name='PlaygroundCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/playground/')),
            ],
        ),
        migrations.CreateModel(
            name='ScienceLabCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/science_lab/')),
            ],
        ),
        migrations.CreateModel(
            name='UniformCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/uniform/')),
            ],
        ),
    ]
