# Generated by Django 6.0 on 2026-01-12 04:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepagecarousel_librarycarousel_playgroundcarousel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarousel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='carousel_homepage'),
        ),
        migrations.AlterField(
            model_name='librarycarousel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='carousel_library'),
        ),
        migrations.AlterField(
            model_name='newscard',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='news_card'),
        ),
        migrations.AlterField(
            model_name='playgroundcarousel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='carousel_playground'),
        ),
        migrations.AlterField(
            model_name='sciencelabcarousel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='carousel_science_lab'),
        ),
        migrations.AlterField(
            model_name='uniformcarousel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='carousel_uniform'),
        ),
    ]
