# Generated by Django 6.0 on 2026-02-28 17:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_homepagecarousel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_routine',
            name='routine',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='routine_file'),
        ),
        migrations.AlterField(
            model_name='class_syllabus',
            name='syllabus',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='syllabus_file'),
        ),
        migrations.AlterField(
            model_name='result',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='result_file'),
        ),
    ]
