# Generated by Django 6.0 on 2026-01-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, upload_to='notice_img/'),
        ),
    ]
